### ISSUE TITLE
Sticky Message

### ISSUE THREAD

**Issue by Hilmomalaya** [Iqrar99/WarnetBot#40]
**Is your feature request related to a problem? Please describe.**
- Terkadang member server tidak melihat topic/ pinned channel sehingga terjadi pelanggaran rules.  Contoh channel untuk ini : #art-genshin-sauce
- Beberapa channel diperlukan Daftar isi/shortcut ke pesan" yang penting agar tidak menumpuk di pinned channel (harus scroll pinned)

**Describe the solution you'd like**
Membuat sticky message yang dapat di atur interval munculnya. contoh: tiap 2 pesan baru.

Contoh sticky note server WFP:
![IMG_20230212_221051](https://user-images.githubusercontent.com/68109788/218320287-1784156f-b164-4741-829c-329732399fbd.jpg)

**Comment by Iqrar99** [comment]
Nice idea! This feature will be good if we use the prefix command.

- `war! stickymsg add <insert text>`: this command will save the message and store it into db or local db like json. The db will contain the message id, channel id where the command is executed, and the message itself.
- `war! stickymsg remove`: will remove the current sticky message in the current channel (if any).

command can only be executed if the user has administrator permission or has a staff role.

**Comment by Irvan789** [comment]
#43
